### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ShixiangWang** [hiplot/hiplotlib#1]
- [x] Hiplot 系统运行流程
- [x] Hiplot 插件启动、运行、关闭流程
- [x] Hiplot 前端UI开放接口
- [x] Hiplot 插件依赖包/工具 选项设定管理
- [x] Hiplot 可视化管理，包括调色板、映射、标尺、主题、导出等
- [ ] Hiplot 插件开发系统，包括基于R的插件生成和解析、与前端接口对接、RStudio Addin/Snippet支持
